name: Fast Forward PR

on:
  issue_comment:
    types: [created]

jobs:
  fast-forward:
    if: github.event.comment.body == '/ff'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Fast Forward PR
        id: ff
        uses: endre-spotlab/fast-forward-js-action@2.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          success_message: 'Código propagado correctamente'
          fail_message: 'No se pudo propagar el código'